import {Orchestrator} from '../lib/agents/orchestrator';
import {ConversationAgent} from '../lib/agents/conversation';
import {parseCSV,IngestionAgent} from '../lib/agents/ingestion';
import {type RawData} from '../lib/agents/types';
declare const SEED:RawData;
declare const ASSET_CONTENT:Record<string,{type:string;body:string}>;
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function readData(env:any){const result=await env.DB.prepare('SELECT source, payload FROM datasets ORDER BY source').all();if(!result.results.length){await persist(env,SEED,new Orchestrator().run(SEED));return SEED;}const raw:any={};for(const r of result.results)raw[r.source]=JSON.parse(r.payload);return raw as RawData;}
async function persist(env:any,raw:RawData,report:any){const now=new Date().toISOString();const statements=Object.entries(raw).map(([source,rows])=>env.DB.prepare('INSERT INTO datasets (source,payload,updated_at) VALUES (?,?,?) ON CONFLICT(source) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at').bind(source,JSON.stringify(rows),now));const clean=new IngestionAgent().run(raw);statements.push(env.DB.prepare('INSERT INTO agent_runs (id,created_at,normalized,outputs) VALUES (?,?,?,?)').bind(crypto.randomUUID(),now,JSON.stringify(clean),JSON.stringify(report)));await env.DB.batch(statements);}
function chatDays(question:string,fallback:number){const q=question.toLowerCase(),words:Record<string,number>={one:1,two:2,three:3,four:4,five:5,six:6};const month=q.match(/last\s+(\d+|one|two|three|four|five|six)\s+months?/),week=q.match(/last\s+(\d+)\s+weeks?/),day=q.match(/last\s+(\d+)\s+days?/);if(month){const value=Number(month[1])||words[month[1]];return Math.min(365,value*30);}if(week)return Math.min(365,Number(week[1])*7);if(day)return Math.min(365,Number(day[1]));return fallback;}
function toolOutput(name:string,report:any){if(name==='query_financial'){const {daily,...financial}=report.finance;return financial;}if(name==='query_demand')return {horizon:report.horizon,asOf:report.quality.end,items:report.forecasts};if(name==='query_anomaly')return report.alerts;if(name==='query_quality')return {...report.quality,issues:report.quality.issues.slice(0,20),totalIssues:report.quality.issues.length};return {actions:report.actions,trace:report.trace};}
export default {async fetch(request:Request,env:any){const url=new URL(request.url);try{
 if(!url.pathname.startsWith('/api/')){const asset=ASSET_CONTENT[url.pathname==='/'?'/index.html':url.pathname];return asset?new Response(asset.body,{headers:{'Content-Type':asset.type,'X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com"}}):new Response('Not found',{status:404});}
 if(!env.DB)return json({error:'Database is unavailable. Please retry after storage is connected.'},503);
 if(request.method==='POST'&&(request.headers.get('sec-fetch-site')==='cross-site'||(request.headers.get('origin')&&request.headers.get('origin')!==url.origin)))return json({error:'Cross-origin requests are not allowed.'},403);
 const days=Number(url.searchParams.get('days')??30),horizon=Number(url.searchParams.get('horizon')??7),category=url.searchParams.get('category')||'All';
 if(![0,7,30,90].includes(days)||![3,5,7].includes(horizon)||!['All','Food','Beverage'].includes(category))return json({error:'Unsupported filter value.'},400);
 if(url.pathname==='/api/report'&&request.method==='GET'){const raw=await readData(env);const report=new Orchestrator().run(raw,days,category,horizon);return json({...report,aiConnected:!!(env.GROQ_API_KEY||env.OPENAI_API_KEY),aiProvider:env.GROQ_API_KEY?'Groq':env.OPENAI_API_KEY?'OpenAI':null,aiModel:env.GROQ_API_KEY?(env.GROQ_MODEL||'openai/gpt-oss-120b'):(env.OPENAI_MODEL||null)});}
 if(url.pathname==='/api/template'&&request.method==='GET'){const source=url.searchParams.get('source') as keyof RawData;if(!['menu','sales','inventory'].includes(source))return json({error:'Unknown source.'},400);const rows=SEED[source];const headers=Object.keys(rows[0]);const csv=[headers.join(','),...rows.slice(0,2).map(row=>headers.map(h=>row[h]).join(','))].join('\n');return new Response(csv,{headers:{'Content-Type':'text/csv','Content-Disposition':`attachment; filename="${source}_template.csv"`}});}
 if(request.method!=='POST')return json({error:'Not found.'},404);
 if(Number(request.headers.get('content-length')||0)>2_000_000)return json({error:'Upload limit is 2 MB.'},413);const text=await request.text();if(text.length>2_000_000)return json({error:'Upload limit is 2 MB.'},413);let body:any;try{body=JSON.parse(text);}catch{return json({error:'Invalid JSON body.'},400);}
 if(url.pathname==='/api/ingest'){const current=await readData(env);let raw:RawData;
 if(body.manual){const {source,row}=body.manual;if(!['sales','inventory'].includes(source)||!row||typeof row!=='object')return json({error:'Invalid manual record.'},400);raw={...current,[source]:[...current[source as keyof RawData],row]};}else{raw={...current};if(!body.files||typeof body.files!=='object')return json({error:'Select a CSV file.'},400);for(const source of Object.keys(body.files)){if(!['menu','sales','inventory'].includes(source)||typeof body.files[source]!=='string')return json({error:'Invalid data source.'},400);raw[source as keyof RawData]=parseCSV(body.files[source]);}}
 const report=new Orchestrator().run(raw,days,category,horizon);if(body.manual){const source=body.manual.source;const rowNum=raw[source as keyof RawData].length+1;const rejected=report.quality.issues.find(i=>i.source===source&&i.row===rowNum);if(rejected)return json({error:`Record rejected: ${rejected.reason}`},400);}
 await persist(env,raw,report);return json({...report,aiConnected:!!(env.GROQ_API_KEY||env.OPENAI_API_KEY),aiProvider:env.GROQ_API_KEY?'Groq':env.OPENAI_API_KEY?'OpenAI':null,aiModel:env.GROQ_API_KEY?(env.GROQ_MODEL||'openai/gpt-oss-120b'):(env.OPENAI_MODEL||null)});}
 if(url.pathname==='/api/run'){const raw=await readData(env);const report=new Orchestrator().run(raw,days,category,horizon);await persist(env,raw,report);return json({...report,aiConnected:!!(env.GROQ_API_KEY||env.OPENAI_API_KEY),aiProvider:env.GROQ_API_KEY?'Groq':env.OPENAI_API_KEY?'OpenAI':null,aiModel:env.GROQ_API_KEY?(env.GROQ_MODEL||'openai/gpt-oss-120b'):(env.OPENAI_MODEL||null)});}
 if(url.pathname==='/api/chat'){if(typeof body.question!=='string'||!body.question.trim()||body.question.length>1500)return json({error:'Enter a question of 1–1,500 characters.'},400);const raw=await readData(env),range=chatDays(body.question,days),report=new Orchestrator().run(raw,range,category,horizon),agent=new ConversationAgent();let answer;try{answer=await agent.run(body.question.trim(),report,{key:env.OPENAI_API_KEY,model:env.OPENAI_MODEL,groqKey:env.GROQ_API_KEY,groqModel:env.GROQ_MODEL,groqResolve:(name,args)=>{const filtered=new Orchestrator().run(raw,Number(args.days??range),String(args.category??category),Number(args.horizon??horizon));return toolOutput(name,filtered);}});}catch(error){const message=error instanceof Error?error.message:'AI provider unavailable';console.error(message);answer={...agent.dataAnswer(body.question.trim(),report),mode:'Data fallback · AI temporarily unavailable',provider:env.GROQ_API_KEY?'Groq':env.OPENAI_API_KEY?'OpenAI':null,model:env.GROQ_MODEL||env.OPENAI_MODEL||null,tools:[],warning:'The AI provider was unavailable, so this answer was calculated directly by the analytics agents.'};}await env.DB.prepare('INSERT INTO conversations (id,created_at,question,answer) VALUES (?,?,?,?)').bind(crypto.randomUUID(),new Date().toISOString(),body.question,JSON.stringify(answer)).run();return json(answer);}
 return json({error:'Not found.'},404);
 }catch(error){const message=error instanceof Error?error.message:'Unexpected failure';console.error(message);return json({error:/column|CSV|rows supplied|usable data|empty|quote/i.test(message)?message:'The request could not finish. Your last saved data is unchanged. '+(/AI provider|reasoning|answer/.test(message)?message:'Please retry.')},/column|CSV|rows supplied|usable data|empty|quote/i.test(message)?400:503);}
 }};
