import {type CleanData,mean,sum,shift,weekday,round} from './types';
export function dailySeries(data:CleanData,id:string){const values=new Map<string,number>();for(const s of data.sales.filter(x=>x.item_id===id))values.set(s.date,(values.get(s.date)||0)+s.quantity_sold);return [...values].sort((a,b)=>a[0].localeCompare(b[0])).map(([date,units])=>({date,units}));}
function predict(history:{date:string;units:number}[],date:string,method:string){const recent=history.filter(x=>x.date>=shift(date,-56)&&x.date<date);const same=recent.filter(x=>weekday(x.date)===weekday(date));const selected=method==='weekday'&&same.length>=3?same:recent.slice(-14);return Math.max(0,mean(selected.map(x=>x.units)));}
export class DemandAgent{
 readonly name='Demand Forecasting';
 run(data:CleanData,horizon=7){return data.menu.map(item=>{
 const history=dailySeries(data,item.item_id);const errors:Record<string,number>={};for(const method of ['weekday','moving']){const holdout=history.filter(x=>x.date>=shift(data.end,-13));errors[method]=mean(holdout.map(p=>Math.abs(p.units-predict(history,p.date,method))));}
 const method=errors.weekday<=errors.moving?'weekday':'moving';const mae=errors[method];const recent=history.filter(x=>x.date>=shift(data.end,-55));const points=Array.from({length:horizon},(_,i)=>{const date=shift(data.end,i+1);const units=Math.round(predict(history,date,method));return {date,units,low:Math.max(0,Math.floor(units-1.5*mae)),high:Math.ceil(units+1.5*mae)};});
 const stock=data.inventory.filter(x=>x.item_id===item.item_id&&x.date<=data.end).at(-1);const sold=stock?history.find(x=>x.date===stock.date)?.units:undefined;const usable=!!stock&&stock.date===data.end&&sold!==undefined;const balance=usable?stock.starting_stock-sold!-stock.wastage_units:null;const closing=balance===null?null:Math.max(0,balance);const daily=mean(points.map(x=>x.units));const lead=stock?.supplier_lead_days||1;const leadDemand=sum(Array.from({length:lead},(_,i)=>predict(history,shift(data.end,i+1),method)));const threshold=Math.ceil(Math.max(stock?.reorder_threshold||0,leadDemand+1.5*mae));const reorder=usable&&balance!==null&&balance>=0&&closing!<threshold;const quantity=reorder?Math.max(0,Math.ceil(leadDemand+daily*2+1.5*mae-closing!)):0;
 return {...item,points,method:method==='weekday'?'Same-weekday average':'14-observation average',mae:round(mae),observations:recent.length,confidence:recent.length>=35?'Moderate':'Low',stockDate:stock?.date||null,closing,balance,lead,threshold,reorder,quantity,coverage:closing!==null&&daily?round(closing/daily):null,total:sum(points.map(x=>x.units)),stockReliable:usable&&balance!==null&&balance>=0};
 });}
}
